# -*- coding: utf-8 -*-
"""Insertion Sorting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/138nGMDbpna6R8B4HNPdnRlbft1lKvXFP
"""

import numpy as np
import time

def viraj_insertion_sort(list):
    for i in range(1, len(list)):
        key = list[i]
        j = i-1
        while j >= 0 and key < list[j]:
            list[j + 1] = list[j]
            j -= 1
            list[j + 1] = key
    return list

n = int(input("Enter length of an array: "))
list = np.random.randint(1,1000,n,dtype=int)
print("Unsorted list is :",list)
print("-------------------------------------------------------------------------------------------------")

start = time.time()
viraj_insertion_sort(list)
print("Sorted list using Insertion Sort is:", list)
print("-------------------------------------------------------------------------------------------------")

end = time.time()
print("Runtime for Insertion Sort is:",end - start, "seconds")

import matplotlib.pyplot as plt
 # Example data
input_sizes = [5, 50, 100, 500, 1000]
# Replace with your input sizes
execution_times = [0.003, 0.002, 0.001, 0.03, 0.13]
# Replace with your measured times
# Create the plot
plt.plot(input_sizes, execution_times, marker='o', linestyle='-')
 # Label the axes and add a title
plt.xlabel('Input Size (n)')
plt.ylabel('Execution Time (seconds)')
plt.title('Sorting Algorithm Benchmark')
# Display the plot
plt.grid(True)
plt.show()