# -*- coding: utf-8 -*-
"""Selection Sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b8IwrlFMN1voA6F_EUYDaMhkAnrajR6e
"""

import numpy as np
import time

def viraj_selection_sort(list):
    for i in range(len(list)):
        min=i
        for j in range (i+1, len(list)):
            if list[min] > list[i]:
                min=j

# Apply swapping formula
        list[i], list[min] = list[min], list[i]
    return list

n = int(input("Enter length of an array: "))
list = np.random.randint(1,1000,n)

print("Unsorted list is: ", list)
print("-------------------------------------------------------------------------------------------------")

start = time.time()
print("Sorted list is:", viraj_selection_sort(list))
print("-------------------------------------------------------------------------------------------------")

end = time.time()
print("Runtime for Selection Sort is:", end - start, "seconds")